// b = 2
// c = 3
try{
    let a = b+c
    console.log({a})
}
catch(err) {
    console.log(err.message);
}
